apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: gigbox
  region: us-east-1

nodeGroups:
  - name: ng-1
    instanceType: m5.4xlarge
    desiredCapacity: 1
  - name: ng-2
    instanceType: m5.large
    desiredCapacity: 1
