apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: gigbox-backend
  region: us-east-1

nodeGroups:
  - name: ng-1
    instanceType: m5.4xlarge
    desiredCapacity: 1
    iam:
      withAddonPolicies:
        externalDNS: true
        certManager: true
  - name: ng-2
    instanceType: m5.large
    desiredCapacity: 1
    iam:
      withAddonPolicies:
        externalDNS: true
        certManager: true
