apiVersion: v1
kind: PersistentVolume
metadata:
  name: gigbox-pv-prod
spec:
  storageClassName: ""
  capacity:
    storage: 100G
  accessModes:
    - ReadWriteOnce
  claimRef:
    namespace: default
    name: server-data-claim-prod
  gcePersistentDisk:
    pdName: gigbox-server-prod
    fsType: ext4
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: server-data-claim-prod
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100G
