version: '3' # Specify docker-compose version
services:
    gigbox-server:
        container_name: gigbox-server
        image: gigbox/gigbox-server:latest
        environment:
            - TWILIO_NUMBER
            - TWILIO_SID
            - TWILIO_TOKEN
            - DB_HOST
            - DB_PORT
            - POSTGRES_USER
            - POSTGRES_PASSWORD
            - POSTGRES_DB
            - ENV
            - SECRET_KEY
            - DATA_DIR=/opt/data
        ports:
            - "80:80"
            - "443:80"
        links:
            - osrm
            - db
        restart: always
        volumes:
            - server-data:/opt/data
        networks:
            - backend
            - frontend
        logging:
            driver: awslogs 
            options:
                awslogs-group: gigbox 
                awslogs-region: us-east-1
                awslogs-stream-prefix: gigbox-server
    db:
        image: postgis/postgis
        ports:
            - '5432'
        volumes:
            - database-data:/var/lib/postgresql/data
        networks:
            - backend
        environment:
            - POSTGRES_USER
            - POSTGRES_PASSWORD
            - POSTGRES_DB
            - ENV
        logging:
            driver: awslogs 
            options:
                awslogs-group: gigbox 
                awslogs-region: us-east-1
                awslogs-stream-prefix: gigbox-db
    osrm:
        container_name: gigbox-osrm
        ## We use 5.24.0 because that's the version we used to extract the OSRM files that we store on 
        ## S3 to reduce deploy times
        image: osrm/osrm-backend:v5.24.0
        restart: always
        command:
            "osrm-routed --max-matching-size 100000 --algorithm mld us-latest.osrm"
        networks:
            - backend
        volumes:
            - osrm-data:/opt
        logging:
            driver: awslogs 
            options:
                awslogs-group: gigbox 
                awslogs-region: us-east-1
                awslogs-stream-prefix: gigbox-osrm
volumes:
    database-data:
    server-data:
    osrm-data:

networks:
    backend:
    frontend:
