---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: osrm-pv
spec:
  storageClassName: ""
  capacity:
    storage: 80G
  accessModes:
    - ReadWriteOnce
  claimRef:
    namespace: default
    name: osrm-claim
  gcePersistentDisk:
    pdName: osrm-disk
    fsType: ext4
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: osrm-claim
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 80G
