apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-gigbox
  namespace: {{ .Release.Namespace }}
  annotations: 
    kubernetes.io/ingress.class: public
    cert-manager.io/issuer: "letsencrypt-prod"
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
spec:
  tls:
  - hosts:
    - {{ .Values.apiHostname }}
    secretName: quickstart-example-tls
  rules:
  - host: {{ .Values.apiHostname }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ .Release.Name }}-gigbox-server
            port:
              number: 80