version: '3.3' # Specify docker-compose version
services:
    gigbox-server:
        container_name: gigbox-server
        image: gigbox/server
        build:
            context: .
            dockerfile: Dockerfile
        # restart: always
        env_file:
            - .env.dev
        ports:
            - '5000:5000'
        command: 'python run.py runserver'
        restart: always
        volumes:
            - .:/usr/src/app
            - server-data:/opt/data
        networks:
            - backend
            - frontend
    db:
        image: postgis/postgis
        env_file: .env
        ports:
            - '5432:5432'
        volumes:
            - database-data:/var/lib/postgresql/data
        networks:
            - backend
    osrm:
        container_name: gigbox-osrm
        image: osrm/osrm-backend 
        restart: always
        ports: 
            - '5001:5000'
        volumes:
            - osrm-data:/opt
        command:
            "osrm-routed --max-matching-size 100000 --algorithm mld us-latest.osrm"
        networks:
            - backend
volumes:
    database-data:
    server-data:
    osrm-data:

networks:
    backend:
    frontend:
