version: '3.3' # Specify docker-compose version
services:
    gigbox-server:
        container_name: gigbox-server
        image: gigbox/gigbox-server-prod
        build:
            context: .
            dockerfile: Dockerfile.prod
        env_file:
            - .env.prod
        ports:
            - '80:80'
        restart: always
        volumes:
            - screenshots:/opt/images
        networks:
            - backend
            - frontend
    db:
        image: postgis/postgis
        env_file: database.env
        ports:
            - '5432:5432'
        volumes:
            - database-data:/var/lib/postgresql/data
        networks:
            - backend
    osrm:
        container_name: gigbox-osrm
        image: osrm/osrm-backend 
        restart: always
        ports:
            - '5001:5000'
        command:
            "osrm-routed --max-matching-size 100000 --algorithm mld us-latest.osrm"
        networks:
            - backend
        volumes:
            - osrm-data:/opt
volumes:
    database-data:
    screenshots:
    osrm-data:

networks:
    backend:
    frontend:
