apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secrets
type: Opaque
stringData:
  TWILIO_NUMBER: {{ .Values.twilioNumber | toString | squote }}
  TWILIO_SID: {{ .Values.twilioSid | quote }}
  TWILIO_TOKEN: {{ .Values.twilioToken | quote }}
  DB_HOST: {{ .Values.dbHost | quote }}
  DB_PORT: {{ .Values.dbPort | quote }}
  POSTGRES_USER: {{ .Values.postgresUser | quote }}
  POSTGRES_PASSWORD: {{ .Values.postgresPassword | quote }}
  POSTGRES_DB: {{ .Values.postgresDbName | quote }}
  OSRM_URI: {{ .Values.osrmUri | default "http://osrm.develop-branch:5000" | quote }}
  SECRET_KEY: {{ .Values.secretKey }}
  ENV: {{ .Values.env }}
