apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app: gigbox-server
  name: s3-provider
spec:
  selector: 
    matchLabels:
      app: gigbox-server
  template:
    metadata:
      labels:
        app: gigbox-server
        tier: data
    spec:
      containers:
      - name: s3fuse
        image: meain/s3-mounter
        securityContext:
          privileged: true
        envFrom:
        - configMapRef:
            name: aws-config
        volumeMounts:
        - name: devfuse
          mountPath: /dev/fuse
        - name: mntdatas3fs
          mountPath: /var/s3fs:shared
      volumes:
      - name: devfuse
        hostPath:
          path: /dev/fuse
      - name: mntdatas3fs
        hostPath:
          path: /mnt/s3data
