"""empty message

Revision ID: 019ba528137a
Revises: e47bdaab2ab1
Create Date: 2021-03-31 15:04:45.692867

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '019ba528137a'
down_revision = 'e47bdaab2ab1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_locations_geom', table_name='locations')
    op.add_column('users', sa.Column('user_id', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'users', ['user_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'user_id')
    op.create_index('idx_locations_geom', 'locations', ['geom'], unique=False)
    # ### end Alembic commands ###
