"""empty message

Revision ID: 040846ac1eae
Revises: b7404922ee7e
Create Date: 2021-04-24 23:43:40.419363

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '040846ac1eae'
down_revision = 'b7404922ee7e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('snapped_geometry', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'snapped_geometry')
    # ### end Alembic commands ###
