"""empty message

Revision ID: 04c235cf8e73
Revises: a2cde87aaa1a
Create Date: 2021-05-14 16:42:09.095261

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '04c235cf8e73'
down_revision = 'a2cde87aaa1a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('consent', 'accelerometer')
    op.drop_column('consent', 'photos')
    op.drop_column('consent', 'survey')
    op.drop_column('consent', 'location')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('consent', sa.Column('location', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('consent', sa.Column('survey', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('consent', sa.Column('photos', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('consent', sa.Column('accelerometer', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
