"""empty message

Revision ID: 070178ec12d8
Revises: e1da5281f84b
Create Date: 2021-05-14 19:25:15.438761

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '070178ec12d8'
down_revision = 'e1da5281f84b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('consent', sa.Column('uid', postgresql.UUID(as_uuid=True), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('consent', 'uid')
    # ### end Alembic commands ###
