"""empty message

Revision ID: 0e09207a3ef0
Revises: e815da2e158a
Create Date: 2021-04-14 17:56:11.933929

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0e09207a3ef0'
down_revision = 'e815da2e158a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('screenshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shift_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('timestamp', sa.String(), nullable=True),
    sa.Column('on_device_uri', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['shift_id'], ['shifts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_index('idx_locations_geom', table_name='locations')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_locations_geom', 'locations', ['geom'], unique=False)
    op.drop_table('screenshots')
    # ### end Alembic commands ###
