"""empty message

Revision ID: 0eb7cba04194
Revises: d398e3959432
Create Date: 2021-05-26 20:51:24.858672

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0eb7cba04194'
down_revision = 'd398e3959432'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('survey_range_options', sa.Column('unit', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('survey_range_options', 'unit')
    # ### end Alembic commands ###
