"""empty message

Revision ID: 239e27b996eb
Revises: f6325e17a809
Create Date: 2021-05-14 19:16:34.035005

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '239e27b996eb'
down_revision = 'f6325e17a809'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    ## Some custom stuff here to convert datetime to a bool
    op.add_column('consent', sa.Column('consented', sa.Boolean(), nullable=True))
    op.alter_column('consent', 'data_sharing',
               existing_type=postgresql.TIMESTAMP(),
               postgresql_using='(CASE when null then true else false end)',
               type_=sa.Boolean(),
               existing_nullable=True)
    op.alter_column('consent', 'interview',
               existing_type=postgresql.TIMESTAMP(),
               postgresql_using='(CASE when null then true else false end)',
               type_=sa.Boolean(),
               existing_nullable=True)
    op.drop_column('consent', 'consent_final_agree')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('consent', sa.Column('consent_final_agree', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.alter_column('consent', 'interview',
               existing_type=sa.Boolean(),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('consent', 'data_sharing',
               existing_type=sa.Boolean(),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.drop_column('consent', 'consented')
    # ### end Alembic commands ###
