"""empty message

Revision ID: 2d6a1e017a9c
Revises: 0e09207a3ef0
Create Date: 2021-04-15 14:51:20.709734

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2d6a1e017a9c'
down_revision = '0e09207a3ef0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('screenshots', sa.Column('img_filename', sa.String(), nullable=True))
    op.add_column('screenshots', sa.Column('user_id', sa.String(), nullable=True))
    op.alter_column('screenshots', 'id',
               existing_type=sa.INTEGER(),
               type_=postgresql.UUID(as_uuid=True),
               existing_nullable=False)
    op.create_foreign_key(None, 'screenshots', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'screenshots', type_='foreignkey')
    op.alter_column('screenshots', 'id',
               existing_type=postgresql.UUID(as_uuid=True),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_column('screenshots', 'user_id')
    op.drop_column('screenshots', 'img_filename')
    # ### end Alembic commands ###
