"""empty message

Revision ID: 2d9e77b9d01f
Revises: d7e1889f234a
Create Date: 2021-04-29 18:23:32.887168

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2d9e77b9d01f'
down_revision = 'd7e1889f234a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('jobs_pay_screenshot_fkey', 'jobs', type_='foreignkey')
    op.drop_column('jobs', 'pay_screenshot')
    op.add_column('screenshots', sa.Column('date_created', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('screenshots', 'date_created')
    op.add_column('jobs', sa.Column('pay_screenshot', postgresql.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key('jobs_pay_screenshot_fkey', 'jobs', 'screenshots', ['pay_screenshot'], ['id'])
    # ### end Alembic commands ###
