"""empty message

Revision ID: 2e1b2046bcb6
Revises: 5bf4b1daafed
Create Date: 2021-05-25 19:16:59.947855

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e1b2046bcb6'
down_revision = '5bf4b1daafed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    #op.drop_table('spatial_ref_sys')
    print("ok")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    print("ok")
    # ### end Alembic commands ###
