"""empty message

Revision ID: 32ba157e3544
Revises: 040846ac1eae
Create Date: 2021-04-26 14:35:41.307696

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '32ba157e3544'
down_revision = '040846ac1eae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('pay_screenshot', postgresql.UUID(as_uuid=True), nullable=True))
    op.create_foreign_key(None, 'jobs', 'screenshots', ['pay_screenshot'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'jobs', type_='foreignkey')
    op.drop_column('jobs', 'pay_screenshot')
    # ### end Alembic commands ###
