"""empty message

Revision ID: 340c63b2e5bc
Revises: ee196639bfb5
Create Date: 2021-05-25 20:44:50.727995

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '340c63b2e5bc'
down_revision = 'ee196639bfb5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table('spatial_ref_sys')
    print("ok")
    op.drop_column('survey_questions', 'select_options')
    op.add_column('survey_questions', sa.Column('select_options', sa.ARRAY(sa.String()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    print("ok")
    # ### end Alembic commands ###
