"""empty message

Revision ID: 38492b627561
Revises: 07622fc0b628
Create Date: 2021-05-14 19:25:44.867401

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '38492b627561'
down_revision = '07622fc0b628'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('consent', sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False))
    op.drop_column('consent', 'uid')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('consent', sa.Column('uid', postgresql.UUID(), autoincrement=False, nullable=False))
    op.drop_column('consent', 'id')
    # ### end Alembic commands ###
