"""empty message

Revision ID: 4521913c37a3
Revises: 7a70d1db1795
Create Date: 2021-03-31 14:00:31.110147

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import geoalchemy2

# revision identifiers, used by Alembic.
revision = '4521913c37a3'
down_revision = '7a70d1db1795'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shifts',
                    sa.Column('id', postgresql.UUID(
                        as_uuid=True), nullable=False),
                    sa.Column('start_time', sa.DateTime(), nullable=False),
                    sa.Column('end_time', sa.DateTime(), nullable=True),
                    sa.Column('user_id', postgresql.UUID(
                        as_uuid=True), nullable=True),
                    sa.Column('active', sa.Boolean(), nullable=False),
                    sa.Column('date_modified', sa.DateTime(), nullable=True),
                    sa.Column('date_created', sa.DateTime(), nullable=True),
                    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('locations',
                    sa.Column('id', postgresql.UUID(
                        as_uuid=True), nullable=False),
                    sa.Column('geom', geoalchemy2.types.Geometry(
                        geometry_type='POINT', from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
                    sa.Column('timestamp', sa.DateTime(), nullable=False),
                    sa.Column('shift_id', postgresql.UUID(
                        as_uuid=True), nullable=True),
                    sa.ForeignKeyConstraint(['shift_id'], ['shifts.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('locations')
    op.drop_table('shifts')
    # ### end Alembic commands ###
