"""empty message

Revision ID: 4ffcd5458bdf
Revises: 008b02e56221
Create Date: 2021-04-16 15:46:45.534379

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ffcd5458bdf'
down_revision = '008b02e56221'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('employers_shift_id_fkey', 'employers', type_='foreignkey')
    op.create_foreign_key(None, 'employers', 'shifts', ['shift_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('screenshots_shift_id_fkey', 'screenshots', type_='foreignkey')
    op.drop_constraint('screenshots_user_id_fkey', 'screenshots', type_='foreignkey')
    op.create_foreign_key(None, 'screenshots', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'screenshots', 'shifts', ['shift_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'screenshots', type_='foreignkey')
    op.drop_constraint(None, 'screenshots', type_='foreignkey')
    op.create_foreign_key('screenshots_user_id_fkey', 'screenshots', 'users', ['user_id'], ['id'])
    op.create_foreign_key('screenshots_shift_id_fkey', 'screenshots', 'shifts', ['shift_id'], ['id'])
    op.drop_constraint(None, 'employers', type_='foreignkey')
    op.create_foreign_key('employers_shift_id_fkey', 'employers', 'shifts', ['shift_id'], ['id'])
    # ### end Alembic commands ###
