"""empty message

Revision ID: 52a56a6a62ab
Revises: 04c235cf8e73
Create Date: 2021-05-14 18:34:17.331142

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '52a56a6a62ab'
down_revision = '04c235cf8e73'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('consent', 'data_sharing',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.Boolean(),
               postgresql_using='data_sharing::boolean',
               existing_nullable=True)
    op.alter_column('consent', 'interview',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.Boolean(),
               postgresql_using='interview::boolean',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('consent', 'interview',
               existing_type=sa.Boolean(),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('consent', 'data_sharing',
               existing_type=sa.Boolean(),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    # ### end Alembic commands ###
