"""empty message

Revision ID: 7626edd5aa45
Revises: d998f82df2e6
Create Date: 2021-03-31 16:38:48.404219

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7626edd5aa45'
down_revision = 'd998f82df2e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('shifts', 'user_id',
               existing_type=postgresql.UUID(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('users', 'id',
               existing_type=postgresql.UUID(),
               type_=sa.String(),
               existing_nullable=False)
    op.drop_constraint('users_user_id_key', 'users', type_='unique')
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=True)
    op.drop_column('users', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('user_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.create_unique_constraint('users_user_id_key', 'users', ['user_id'])
    op.alter_column('users', 'id',
               existing_type=sa.String(),
               type_=postgresql.UUID(),
               existing_nullable=False)
    op.alter_column('shifts', 'user_id',
               existing_type=sa.String(),
               type_=postgresql.UUID(),
               existing_nullable=True)
    # ### end Alembic commands ###
