"""empty message

Revision ID: 7c24467f509a
Revises: e1dddc3b72de
Create Date: 2021-04-24 02:10:43.969976

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c24467f509a'
down_revision = 'e1dddc3b72de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trips', sa.Column('end_time', sa.DateTime(), nullable=True))
    op.add_column('trips', sa.Column('estimated_mileage', sa.Float(), nullable=True))
    op.add_column('trips', sa.Column('start_time', sa.DateTime(), nullable=True))
    op.drop_column('trips', 'is_work')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trips', sa.Column('is_work', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('trips', 'start_time')
    op.drop_column('trips', 'estimated_mileage')
    op.drop_column('trips', 'end_time')
    # ### end Alembic commands ###
