"""empty message

Revision ID: 8370bf03b272
Revises: 2d9e77b9d01f
Create Date: 2021-04-29 21:02:02.327242

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8370bf03b272'
down_revision = '2d9e77b9d01f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('jobs_end_screenshot_fkey', 'jobs', type_='foreignkey')
    op.drop_constraint('jobs_start_screenshot_fkey', 'jobs', type_='foreignkey')
    op.drop_column('jobs', 'end_screenshot')
    op.drop_column('jobs', 'start_screenshot')
    op.add_column('screenshots', sa.Column('job_id', postgresql.UUID(as_uuid=True), nullable=True))
    op.create_foreign_key(None, 'screenshots', 'jobs', ['job_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'screenshots', type_='foreignkey')
    op.drop_column('screenshots', 'job_id')
    op.add_column('jobs', sa.Column('start_screenshot', postgresql.UUID(), autoincrement=False, nullable=True))
    op.add_column('jobs', sa.Column('end_screenshot', postgresql.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key('jobs_start_screenshot_fkey', 'jobs', 'screenshots', ['start_screenshot'], ['id'])
    op.create_foreign_key('jobs_end_screenshot_fkey', 'jobs', 'screenshots', ['end_screenshot'], ['id'])
    # ### end Alembic commands ###
