"""empty message

Revision ID: 8845ab927ba5
Revises: 38492b627561
Create Date: 2021-05-14 19:27:16.464435

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8845ab927ba5'
down_revision = '38492b627561'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('consent', sa.Column('signature_encoded', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('consent', 'signature_encoded')
    # ### end Alembic commands ###
