"""empty message

Revision ID: 9b6c1e302081
Revises: 8845ab927ba5
Create Date: 2021-05-17 15:11:31.097140

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9b6c1e302081'
down_revision = '8845ab927ba5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('employers')
    op.add_column('users', sa.Column('employers', postgresql.ARRAY(sa.Enum('DOORDASH', 'INSTACART', 'SHIPT', 'GRUBHUB', 'UBEREATS', name='employernames', native_enum=False)), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'employers')
    op.create_table('employers',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('shift_id', postgresql.UUID(), autoincrement=False, nullable=True),
    sa.Column('name', postgresql.ENUM('DOORDASH', 'INSTACART', 'SHIPT', 'GRUBHUB', 'UBEREATS', name='employernames'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['shift_id'], ['shifts.id'], name='employers_shift_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='employers_pkey')
    )
    # ### end Alembic commands ###
