"""empty message

Revision ID: a2cde87aaa1a
Revises: 1b5dc18dc6f7
Create Date: 2021-05-14 16:35:27.704895

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a2cde87aaa1a'
down_revision = '1b5dc18dc6f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('consent', sa.Column('accelerometer', sa.DateTime(), nullable=True))
    op.add_column('consent', sa.Column('survey', sa.DateTime(), nullable=True))
    op.drop_column('consent', 'accelerometery')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('consent', sa.Column('accelerometery', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('consent', 'survey')
    op.drop_column('consent', 'accelerometer')
    # ### end Alembic commands ###
