"""empty message

Revision ID: d398e3959432
Revises: 340c63b2e5bc
Create Date: 2021-05-26 13:57:10.105606

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd398e3959432'
down_revision = '340c63b2e5bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('survey_survey', sa.Column('days_after_install', sa.Integer(), nullable=True))
    op.add_column('survey_survey', sa.Column('description', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('survey_survey', 'description')
    op.drop_column('survey_survey', 'days_after_install')
    # ### end Alembic commands ###
