"""empty message

Revision ID: d6b52c73a522
Revises: 5af1dac55080
Create Date: 2021-04-07 10:17:05.543821

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd6b52c73a522'
down_revision = '5af1dac55080'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employer', sa.Enum('DOORDASH', 'INSTACART', 'SHIPT', 'GRUBHUB', 'UBEREATS', name='employers'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_foreign_key(None, 'locations', 'shifts', ['shift_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'locations', type_='foreignkey')
    op.drop_table('employers')
    # ### end Alembic commands ###
