"""empty message

Revision ID: d7e1889f234a
Revises: 32ba157e3544
Create Date: 2021-04-26 15:56:55.176622

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd7e1889f234a'
down_revision = '32ba157e3544'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('employers')
    op.add_column('shifts', sa.Column('employers', postgresql.ARRAY(sa.Enum('DOORDASH', 'INSTACART', 'SHIPT', 'GRUBHUB', 'UBEREATS', name='employernames', native_enum=False)), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shifts', 'employers')
    op.create_table('employers',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('shift_id', postgresql.UUID(), autoincrement=False, nullable=True),
    sa.Column('name', postgresql.ENUM('DOORDASH', 'INSTACART', 'SHIPT', 'GRUBHUB', 'UBEREATS', name='employernames'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['shift_id'], ['shifts.id'], name='employers_shift_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='employers_pkey')
    )
    # ### end Alembic commands ###
