"""empty message

Revision ID: d998f82df2e6
Revises: 464c34f0b830
Create Date: 2021-03-31 16:37:28.028731

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd998f82df2e6'
down_revision = '464c34f0b830'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'id',
               existing_type=postgresql.UUID(),
               type_=sa.String(),
               existing_nullable=False)
    op.drop_index('ix_users_user_id', table_name='users')
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=True)
    op.drop_column('users', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('user_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.create_index('ix_users_user_id', 'users', ['user_id'], unique=True)
    op.alter_column('users', 'id',
               existing_type=sa.String(),
               type_=postgresql.UUID(),
               existing_nullable=False)
    # ### end Alembic commands ###
