"""empty message

Revision ID: e1868f62ca7d
Revises: 20c0b1512158
Create Date: 2021-04-07 15:46:42.229602

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1868f62ca7d'
down_revision = '20c0b1512158'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('index', 'shifts', ['id', 'start_time'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('index', table_name='shifts')
    # ### end Alembic commands ###
