"""empty message

Revision ID: e1da5281f84b
Revises: 239e27b996eb
Create Date: 2021-05-14 19:23:58.490484

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e1da5281f84b'
down_revision = '239e27b996eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('consent', 'id',
               existing_type=sa.VARCHAR(),
               type_=postgresql.UUID(as_uuid=True),
               existing_nullable=False)
    op.drop_index('ix_consent_id', table_name='consent')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_consent_id', 'consent', ['id'], unique=True)
    op.alter_column('consent', 'id',
               existing_type=postgresql.UUID(as_uuid=True),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    # ### end Alembic commands ###
