"""empty message

Revision ID: e1dddc3b72de
Revises: 4ffcd5458bdf
Create Date: 2021-04-23 19:47:10.938599

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e1dddc3b72de'
down_revision = '4ffcd5458bdf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_locations_geom', table_name='locations')
    op.add_column('shifts', sa.Column('snapped_geometry', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.drop_index('idx_trips_end_location', table_name='trips')
    op.drop_index('idx_trips_start_location', table_name='trips')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_trips_start_location', 'trips', ['start_location'], unique=False)
    op.create_index('idx_trips_end_location', 'trips', ['end_location'], unique=False)
    op.drop_column('shifts', 'snapped_geometry')
    op.create_index('idx_locations_geom', 'locations', ['geom'], unique=False)
    # ### end Alembic commands ###
