"""empty message

Revision ID: e47bdaab2ab1
Revises: fc15e62ff421
Create Date: 2021-03-31 15:00:43.271450

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e47bdaab2ab1'
down_revision = 'fc15e62ff421'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'id',
               existing_type=postgresql.UUID(),
               type_=sa.String(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'id',
               existing_type=sa.String(),
               type_=postgresql.UUID(),
               existing_nullable=False)
    # ### end Alembic commands ###
