"""empty message

Revision ID: e815da2e158a
Revises: e1868f62ca7d
Create Date: 2021-04-08 09:07:37.058165

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e815da2e158a'
down_revision = 'e1868f62ca7d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('locations', sa.Column('accuracy', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('locations', 'accuracy')
    # ### end Alembic commands ###
