"""empty message

Revision ID: ee196639bfb5
Revises: 2e1b2046bcb6
Create Date: 2021-05-25 20:32:29.733774

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ee196639bfb5'
down_revision = '2e1b2046bcb6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('survey_questions', 'multiselect_options')
    op.drop_column('survey_questions', 'select_options')
    op.add_column('survey_questions', 'select_options')
    sa.Column('select_options', sa.ARRAY(sa.String()), nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('survey_questions', sa.Column('multiselect_options', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True))
        # ### end Alembic commands ###
