"""empty message

Revision ID: f6325e17a809
Revises: 52a56a6a62ab
Create Date: 2021-05-14 19:04:26.125695

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f6325e17a809'
down_revision = '52a56a6a62ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('consent', sa.Column('consented', sa.Boolean(), nullable=True))
    op.alter_column('consent', 'data_sharing',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.Boolean(),
               postgresql_using='(CASE when data_sharing then 1 else 0 end)',
               existing_nullable=True)
    op.alter_column('consent', 'interview',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.Boolean(),
               postgresql_using='(CASE when interview then 1 else 0 end)',
               existing_nullable=True)
    op.drop_column('consent', 'consent_final_agree')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('consent', sa.Column('consent_final_agree', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.alter_column('consent', 'interview',
               existing_type=sa.Boolean(),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('consent', 'data_sharing',
               existing_type=sa.Boolean(),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.drop_column('consent', 'consented')
    # ### end Alembic commands ###
