"""empty message

Revision ID: fc15e62ff421
Revises: 4521913c37a3
Create Date: 2021-03-31 14:58:07.145778

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc15e62ff421'
down_revision = '4521913c37a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_locations_geom', table_name='locations')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_locations_geom', 'locations', ['geom'], unique=False)
    # ### end Alembic commands ###
