apiVersion: v1
kind: PersistentVolume
metadata:
  name: gigbox-pv-dev
  namespace: development
spec:
  storageClassName: ""
  capacity:
    storage: 100G
  accessModes:
    - ReadWriteOnce
  claimRef:
    namespace: development
    name: server-data-claim-dev
  gcePersistentDisk:
    pdName: gigbox-server-dev
    fsType: ext4
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: server-data-claim-dev
  namespace: development
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100G

