name: 'Deploy'
on: ['deployment']

jobs:
  build-and-push:
      name: Build and push to Docker Hub
      runs-on: ubuntu-latest
      steps:
        - 
          name: Checkout
          uses: actions/checkout@master
        -
          name: Set up QEMU
          uses: docker/setup-qemu-action@v1
        -
          name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v1
        -
          name: Login to DockerHub
          uses: docker/login-action@v1 
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}
        -
          name: Build and push
          id: docker_build
          uses: docker/build-push-action@v2
          with:
            push: true
            context: ./server
            file: ./server/Dockerfile
            tags: gigbox/gigbox-server:${{secrets.DOCKER_IMAGE_TAG}}
        -
          name: Image digest
          run: echo ${{ steps.docker_build.outputs.digest }}
  deployment:
    runs-on: 'ubuntu-latest'
    needs: build-and-push
    steps:
    - name: 'Checkout'
      uses: 'actions/checkout@v1'

    - name: 'Deploy'
      # Parameters are pulled directly from the GitHub deployment event so the
      # configuration for the job here is very minimal.
      uses: 'deliverybot/helm@master'
      with:
        token: '${{ github.token }}'
        secrets: '${{ toJSON(secrets) }}'
        version: '${{ github.sha }}'
        chart: 'chart/gigbox-chart'
      env:
        KUBECONFIG_FILE: '${{ secrets.KUBECONFIG }}'